config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
   end

   resource :user, except: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '東北' },
    { id: 4, name: '関東甲信越' },
    { id: 5, name: '中京' },
    { id: 6, name: '北陸' },
    { id: 7, name: '関西' },
    { id: 8, name: '中国・四国・九州' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/generation.rb
class Generation < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代以上' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments

  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  belongs_to :prefecture
  belongs_to :weather
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }

  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :comments

         validates :nickname, presence: true
         validates :birth_day, presence: true
         validates :favorites_ski_resort, presence: true


         extend ActiveHash::Associations::ActiveRecordExtensions
         belongs_to :generation
         

         validates :generation_id, numericality: { other_than: 1 }

end

app/models/weather.rb
class Weather < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '快晴' },
    { id: 3, name: '晴れ' },
    { id: 4, name: '曇り' },
    { id: 5, name: '雪' },
    { id: 6, name: 'ガス' },
    { id: 7, name: '雨' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birth_day, :generation_id, :favorites_ski_resort])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      @comments = @post.comments
      render 'posts/show'
    end
  end


  private 
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_post, only: [:edit, :show, :update, :destroy]

  def index
    @posts = Post.all
    @posts = Post.order('created_at DESC')

  end 

  def new
    @post = Post.new
  end

  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit 
  end

  def update

    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
    private

    def post_params
      params.require(:post).permit(:ski_resort_name, :area_id, :prefecture_id, :image, :weather_id, :thoughts ).merge(user_id: current_user.id)
    end
  
    def set_post
      @post = Post.find(params[:id])
    end


end



   

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザー情報を更新しました。'
    else
      render :edit
    end

  end

  private
  
      def user_params
        params.require(:user).permit(:nickname, :email, :birth_day, :generation_id, :favorites_ski_resort)

      end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snowbordingapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/69783dde2e.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="site-header sticky-top py-1">
  <nav class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="py-2" href="/" aria-label="Product">
      <i class="fa-solid fa-person-snowboarding fa-2xl fa-beat"></i></a>
    <a class="py-2 d-none d-md-inline-block" href="#">お気に入りスキー場</a>
    <a class="py-2 d-none d-md-inline-block" href="#">滑走回数</a>
    <a class="py-2 d-none d-md-inline-block" href="#">滑走距離</a>
    <a class="py-2 d-none d-md-inline-block" href="#">友達</a>
    <a class="py-2 d-none d-md-inline-block" href="#">スキー場を検索する</a>
    
  <% if user_signed_in? %>
      <%= link_to( user_path) do %>
       <button type="button" class="btn btn-outline-primary">welcome ! <%=current_user.nickname%></button>
      <% end %>
    
              
    <%= link_to( destroy_user_session_path, method: :delete ) do %>
       <button type="button" class="btn btn-outline-secondary"><%='logout'%></button>
    <% end %>
  <% else %>
    <%= link_to( new_user_session_path) do %>
       <button type="button" class="btn btn-link">ログイン</button>
    <% end %>
    <%= link_to( new_user_registration_path) do %>
      <button type="button" class="btn btn-link">新規登録</button>
    <% end %>
  <% end %>
  </nav> 
</header>

    <%= yield %>

   <footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2017–2021</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Cool stuff</a></li>
        <li><a class="link-secondary" href="#">Random feature</a></li>
        <li><a class="link-secondary" href="#">Team feature</a></li>
        <li><a class="link-secondary" href="#">Stuff for developers</a></li>
        <li><a class="link-secondary" href="#">Another one</a></li>
        <li><a class="link-secondary" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Resource name</a></li>
        <li><a class="link-secondary" href="#">Resource</a></li>
        <li><a class="link-secondary" href="#">Another resource</a></li>
        <li><a class="link-secondary" href="#">Final resource</a></li>
      </ul>
    </div>
  </div>
</footer>

  </body>
</html>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">

  <h1><i class="fa-solid fa-pen  fa-beat"></i>おすすめのスキー場を記録<i class="fa-solid fa-pen  fa-beat"></i></h1>
  <%=form_with model: @post, local: true do |f|%>



     <div class="form-group">
    <%= f.label :ski_resort_name, "スキー場名" %><br />
    <%= f.text_field :ski_resort_name, id:"ski_resort_name",placeholder:"ゲレンデ名", autofocus: true, autocomplete: "height", class: "form-control"  %>
     </div>
   
    <div class="form-group">
    <%= f.label :area_id, "エリア" %><br />
    <%= f.collection_select :area_id, Area.all, :id, :name, {}, class: "form-control" %>
    </div>

     <div class="form-group">
    <%= f.label :prefecture_id , "都道府県" %><br />
    <%= f.collection_select :prefecture_id ,Prefecture.all, :id, :name, {}, class: "form-control"%>
    </div>

   


     <div class="form-group">
    <%= f.label :weather_id , "天気" %><br />
    <%= f.collection_select :weather_id , Weather.all, :id, :name, {}, class: "form-control"  %>
    </div>

  <div class="form-group">
     <%= f.label :thoughts , "感想・備考欄" %><br />
     <%= f.text_area :thoughts, class:"text", id:"record_thoughts", placeholder:"スキー場の感想・メモ" ,rows:"7" ,maxlength:"1000" ,class: "form-control"%>
  </div>

   <div class="form-group">
     <%= f.label :image , "画像を添付" %><br />
     <%= f.file_field :image, id:"post-image", class: "form-control" %>
   </div>

      <div>  
         <div class="d-grid gap-2 col-6 mx-auto">
          <%= f.submit "投稿を編集する", class: "btn btn-primary" %>
           <%=link_to 'もどる', post_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  
 <% end %>
</div>
</div>
</div>

app/views/posts/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Product example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
  </head>
  <body>
   
  
<main>
  <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 fw-normal">スキー場をシェアしよう！</h1>
      <p class="lead fw-normal">あなたがおすすめする全国のスキー場を紹介しよう！</p>
     
       <%= link_to( new_post_path) do %>
          <span class="btn btn-outline-secondary">滑走を記録する</span>
       <% end %>


    </div>
    <div class="product-device shadow-sm d-none d-md-block"></div>
    <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  </div>


<% @posts.each do |post| %>
   
 

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
      <div class="my-3 p-3">
  
       <div >
      <p>スキー場名: <%= post.ski_resort_name %></p>
    </div>
    <div>
      <p>エリア: <%= post.area.name %></p>
    </div>
    <div>
      <p>都道府県: <%= post.prefecture.name %></p>
    </div>
    <div>
      <p>天候: <%= post.weather.name %></p>
    </div>
    <div >
      <p>メモ: <%= post.thoughts %></p>
    </div>

      <%= image_tag post.image.variant(resize: '500x500'), class: "item-img" if post.image.attached? %>

      </div>


         <div>
         <button type="button" class="btn btn-secondary btn-sm">投稿者 <%=post.user.nickname%></button>
        </div>

    <div>
     <% if user_signed_in? %>
              
                <div class="btn-group">
                 <%= link_to( post_path(post.id), method: :get ) do %>
                  <button type="button" class="btn btn-outline-primary"> <%='view more' %></button>
                 <% end %>
                </div>
      <% end %>
    </div>
   </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

 <% end %>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-primary me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>
</main>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">

  <h1><i class="fa-solid fa-pen  fa-beat"></i>おすすめのスキー場を記録<i class="fa-solid fa-pen  fa-beat"></i></h1>
  <%=form_with model: @post, url: posts_path, local: true do |f|%>



     <div class="form-group">
    <%= f.label :ski_resort_name, "スキー場名" %><br />
    <%= f.text_field :ski_resort_name, id:"ski_resort_name",placeholder:"ゲレンデ名", autofocus: true, autocomplete: "height", class: "form-control"  %>
     </div>
   
    <div class="form-group">
    <%= f.label :area_id, "エリア" %><br />
    <%= f.collection_select :area_id, Area.all, :id, :name, {}, class: "form-control" %>
    </div>

     <div class="form-group">
    <%= f.label :prefecture_id , "都道府県" %><br />
    <%= f.collection_select :prefecture_id ,Prefecture.all, :id, :name, {}, class: "form-control"%>
    </div>

   


     <div class="form-group">
    <%= f.label :weather_id , "天気" %><br />
    <%= f.collection_select :weather_id , Weather.all, :id, :name, {}, class: "form-control"  %>
    </div>

  <div class="form-group">
     <%= f.label :thoughts , "感想・備考欄" %><br />
     <%= f.text_area :thoughts, class:"text", id:"record_thoughts", placeholder:"スキー場の感想・メモ" ,rows:"7" ,maxlength:"1000" ,class: "form-control"%>
  </div>

   <div class="form-group">
     <%= f.label :image , "画像を添付" %><br />
     <%= f.file_field :image, id:"post-image", class: "form-control" %>
   </div>

      <div>  
        <div class="d-grid gap-2 col-6 mx-auto">
          <%= f.submit "記録する", class: "btn btn-dark" %>
        </div>
      </div>
    </div>
  
 <% end %>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="album py-5 bg-light ">
  
    <div class="container">

      <div class="row row-cols- row-cols-sm-2 g-2 justify-content-center ">

        <div class="col">
          <div class="card shadow-sm">

             <%= image_tag @post.image %>

                <div class="card-body">
                  <p>
                    <div class = "record-days" >
                       <p>スキー場名: <%= @post.ski_resort_name %></p>
                    </div>
                    <div>
                       <p>エリア: <%= @post.area.name %></p>
                    </div>
                    <div>
                     <p>都道府県: <%= @post.prefecture.name %></p>
                    </div>
                     <div >
                      <p>天候: <%= @post.weather.name %></p>
                    </div>
                     <div >
                      <p>メモ: <%= @post.thoughts %></p>
                    </div>
      
                  </p>   
          
                <% if @post.user == current_user %>
                   <p>
                    <%= link_to( edit_post_path) do %>
                  <button type="button" class="btn btn-warning">記録を編集</button>
                    <% end %>

                     <%= link_to post_path, method: :delete  do %>
                    <button type="button" class="btn btn-success">記録を削除</button>
                    <% end %>
                    </p>
                <% end %>
                         

          
      </div>                  
    </div>
</div>

            <div class="container">
             <div class="row row-cols- row-cols-sm-2 g-2 justify-content-center ">
              <div class="col">
               <div class="card shadow-sm">
                <div class="card-body">
                  <% if user_signed_in? %>
                    <%= form_with(model: [@post, @comment], local: true) do |form| %>
                        <div class="form-group">
                          <%= form.text_area :text, placeholder: "コメントする", rows: "2" ,class: "form-control"%>
                        </div>
                         <div class="d-grid gap-2 col-6 mx-auto">
                          <%= form.submit "SEND", class: "btn btn-outline-secondary" %>
                        </div>
                    <% end %>
                  <% else %>
                    <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
                  <% end %>
                  <div class="comments">
                    <h4>＜コメント一覧＞</h4>
                    <% @comments.each do |comment| %>
                      <p>
                        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                        <%= comment.text %>
                      </p>
                    <% end %>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
    </div>
   </div>
                 

app/views/users/edit.html.erb
 

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h1>ユーザー情報編集<i class="fa-solid fa-user"></i></h1>
      <%= form_with model: @user, local: true do |f| %>

        <div class="form-group">
           <%= f.label :name, "ニックネーム" %><br />
          <%= f.text_field :nickname, autofocus: true, class: "form-control" %>
        </div>

        <div class="form-group">
        <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password, "パスワード（6文字以上）" %><br />
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
        </div>

        <div class="form-group">
         <%= f.label :birth_day, "誕生日" %><br />
         <%= f.date_field  :birth_day, class: "form-control"%>
        </div>

         <div class="form-group">
           <%= f.label :generation_id, "年齢" %><br />
         <%= f.collection_select :generation_id, Generation.all, :id, :name, {}, class: "form-control" %>
        </div>

       <div class="form-group">
         <%= f.label :favorites_ski_resort, "よく行くスキー場" %><br />
         <%= f.text_field :favorites_ski_resort, id:"user_body_weight", autofocus: true, autocomplete: "body_weight", class: "form-control" %>
       </div>
        </div>
       <div>
          <%= f.submit class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>












  

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">ニックネーム<%= current_user.nickname %></h5>
          <h6 class="card-subtitle mb-2 text-muted">登録メールアドレス<%= current_user.email %></h6>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.birth_day %>生まれ</h6>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.generation.name %></h6>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.favorites_ski_resort %>スキー場</h6>
          <%= link_to( edit_user_path) do %>
            <button type="button" class="btn btn-outline-primary"><%='編集'%></button>
          <% end %>
        </div>    
      </div>
    </div> 
   </div>
 </div>